/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutSessionsIndexImport } from './routes/_layout/sessions/index'
import { Route as LayoutSessionsSessionIdImport } from './routes/_layout/sessions/$sessionId'
import { Route as LayoutProjectsLayoutProjectsImport } from './routes/_layout/projects/_layout-projects'
import { Route as LayoutModelsLayoutModelsImport } from './routes/_layout/models/_layout-models'
import { Route as LayoutDataLayoutDatasourcesImport } from './routes/_layout/data/_layout-datasources'
import { Route as LayoutAnalyticsLayoutModelsImport } from './routes/_layout/analytics/_layout-models'
import { Route as LayoutProjectsLayoutProjectsIndexImport } from './routes/_layout/projects/_layout-projects/index'
import { Route as LayoutModelsLayoutModelsIndexImport } from './routes/_layout/models/_layout-models/index'
import { Route as LayoutDataLayoutDatasourcesIndexImport } from './routes/_layout/data/_layout-datasources/index'
import { Route as LayoutAnalyticsLayoutModelsIndexImport } from './routes/_layout/analytics/_layout-models/index'
import { Route as LayoutProjectsLayoutProjectsProjectIdImport } from './routes/_layout/projects/_layout-projects/$projectId'
import { Route as LayoutDataLayoutDatasourcesDataSourceIdImport } from './routes/_layout/data/_layout-datasources/$dataSourceId'
import { Route as LayoutChatProjectsProjectIdImport } from './routes/_layout/chat/projects/$projectId'

// Create Virtual Routes

const LayoutProjectsImport = createFileRoute('/_layout/projects')()
const LayoutModelsImport = createFileRoute('/_layout/models')()
const LayoutDataImport = createFileRoute('/_layout/data')()
const LayoutAnalyticsImport = createFileRoute('/_layout/analytics')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_layout.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LayoutProjectsRoute = LayoutProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutModelsRoute = LayoutModelsImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDataRoute = LayoutDataImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAnalyticsRoute = LayoutAnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSessionsIndexRoute = LayoutSessionsIndexImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/sessions/index.lazy').then((d) => d.Route),
)

const LayoutSessionsSessionIdRoute = LayoutSessionsSessionIdImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/sessions/$sessionId.lazy').then((d) => d.Route),
)

const LayoutProjectsLayoutProjectsRoute =
  LayoutProjectsLayoutProjectsImport.update({
    id: '/_layout-projects',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)

const LayoutModelsLayoutModelsRoute = LayoutModelsLayoutModelsImport.update({
  id: '/_layout-models',
  getParentRoute: () => LayoutModelsRoute,
} as any)

const LayoutDataLayoutDatasourcesRoute =
  LayoutDataLayoutDatasourcesImport.update({
    id: '/_layout-datasources',
    getParentRoute: () => LayoutDataRoute,
  } as any)

const LayoutAnalyticsLayoutModelsRoute =
  LayoutAnalyticsLayoutModelsImport.update({
    id: '/_layout-models',
    getParentRoute: () => LayoutAnalyticsRoute,
  } as any)

const LayoutProjectsLayoutProjectsIndexRoute =
  LayoutProjectsLayoutProjectsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProjectsLayoutProjectsRoute,
  } as any).lazy(() =>
    import('./routes/_layout/projects/_layout-projects/index.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutModelsLayoutModelsIndexRoute =
  LayoutModelsLayoutModelsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutModelsLayoutModelsRoute,
  } as any).lazy(() =>
    import('./routes/_layout/models/_layout-models/index.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutDataLayoutDatasourcesIndexRoute =
  LayoutDataLayoutDatasourcesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutDataLayoutDatasourcesRoute,
  } as any).lazy(() =>
    import('./routes/_layout/data/_layout-datasources/index.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutAnalyticsLayoutModelsIndexRoute =
  LayoutAnalyticsLayoutModelsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAnalyticsLayoutModelsRoute,
  } as any).lazy(() =>
    import('./routes/_layout/analytics/_layout-models/index.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutProjectsLayoutProjectsProjectIdRoute =
  LayoutProjectsLayoutProjectsProjectIdImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => LayoutProjectsLayoutProjectsRoute,
  } as any).lazy(() =>
    import('./routes/_layout/projects/_layout-projects/$projectId.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutDataLayoutDatasourcesDataSourceIdRoute =
  LayoutDataLayoutDatasourcesDataSourceIdImport.update({
    id: '/$dataSourceId',
    path: '/$dataSourceId',
    getParentRoute: () => LayoutDataLayoutDatasourcesRoute,
  } as any).lazy(() =>
    import('./routes/_layout/data/_layout-datasources/$dataSourceId.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutChatProjectsProjectIdRoute =
  LayoutChatProjectsProjectIdImport.update({
    id: '/chat/projects/$projectId',
    path: '/chat/projects/$projectId',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/chat/projects/$projectId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/analytics/_layout-models': {
      id: '/_layout/analytics/_layout-models'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsLayoutModelsImport
      parentRoute: typeof LayoutAnalyticsRoute
    }
    '/_layout/data': {
      id: '/_layout/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof LayoutDataImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/data/_layout-datasources': {
      id: '/_layout/data/_layout-datasources'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof LayoutDataLayoutDatasourcesImport
      parentRoute: typeof LayoutDataRoute
    }
    '/_layout/models': {
      id: '/_layout/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof LayoutModelsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/models/_layout-models': {
      id: '/_layout/models/_layout-models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof LayoutModelsLayoutModelsImport
      parentRoute: typeof LayoutModelsRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects/_layout-projects': {
      id: '/_layout/projects/_layout-projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsLayoutProjectsImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/sessions/$sessionId': {
      id: '/_layout/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof LayoutSessionsSessionIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sessions/': {
      id: '/_layout/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/chat/projects/$projectId': {
      id: '/_layout/chat/projects/$projectId'
      path: '/chat/projects/$projectId'
      fullPath: '/chat/projects/$projectId'
      preLoaderRoute: typeof LayoutChatProjectsProjectIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/data/_layout-datasources/$dataSourceId': {
      id: '/_layout/data/_layout-datasources/$dataSourceId'
      path: '/$dataSourceId'
      fullPath: '/data/$dataSourceId'
      preLoaderRoute: typeof LayoutDataLayoutDatasourcesDataSourceIdImport
      parentRoute: typeof LayoutDataLayoutDatasourcesImport
    }
    '/_layout/projects/_layout-projects/$projectId': {
      id: '/_layout/projects/_layout-projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsLayoutProjectsProjectIdImport
      parentRoute: typeof LayoutProjectsLayoutProjectsImport
    }
    '/_layout/analytics/_layout-models/': {
      id: '/_layout/analytics/_layout-models/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof LayoutAnalyticsLayoutModelsIndexImport
      parentRoute: typeof LayoutAnalyticsLayoutModelsImport
    }
    '/_layout/data/_layout-datasources/': {
      id: '/_layout/data/_layout-datasources/'
      path: '/'
      fullPath: '/data/'
      preLoaderRoute: typeof LayoutDataLayoutDatasourcesIndexImport
      parentRoute: typeof LayoutDataLayoutDatasourcesImport
    }
    '/_layout/models/_layout-models/': {
      id: '/_layout/models/_layout-models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof LayoutModelsLayoutModelsIndexImport
      parentRoute: typeof LayoutModelsLayoutModelsImport
    }
    '/_layout/projects/_layout-projects/': {
      id: '/_layout/projects/_layout-projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsLayoutProjectsIndexImport
      parentRoute: typeof LayoutProjectsLayoutProjectsImport
    }
  }
}

// Create and export the route tree

interface LayoutAnalyticsLayoutModelsRouteChildren {
  LayoutAnalyticsLayoutModelsIndexRoute: typeof LayoutAnalyticsLayoutModelsIndexRoute
}

const LayoutAnalyticsLayoutModelsRouteChildren: LayoutAnalyticsLayoutModelsRouteChildren =
  {
    LayoutAnalyticsLayoutModelsIndexRoute:
      LayoutAnalyticsLayoutModelsIndexRoute,
  }

const LayoutAnalyticsLayoutModelsRouteWithChildren =
  LayoutAnalyticsLayoutModelsRoute._addFileChildren(
    LayoutAnalyticsLayoutModelsRouteChildren,
  )

interface LayoutAnalyticsRouteChildren {
  LayoutAnalyticsLayoutModelsRoute: typeof LayoutAnalyticsLayoutModelsRouteWithChildren
}

const LayoutAnalyticsRouteChildren: LayoutAnalyticsRouteChildren = {
  LayoutAnalyticsLayoutModelsRoute:
    LayoutAnalyticsLayoutModelsRouteWithChildren,
}

const LayoutAnalyticsRouteWithChildren = LayoutAnalyticsRoute._addFileChildren(
  LayoutAnalyticsRouteChildren,
)

interface LayoutDataLayoutDatasourcesRouteChildren {
  LayoutDataLayoutDatasourcesDataSourceIdRoute: typeof LayoutDataLayoutDatasourcesDataSourceIdRoute
  LayoutDataLayoutDatasourcesIndexRoute: typeof LayoutDataLayoutDatasourcesIndexRoute
}

const LayoutDataLayoutDatasourcesRouteChildren: LayoutDataLayoutDatasourcesRouteChildren =
  {
    LayoutDataLayoutDatasourcesDataSourceIdRoute:
      LayoutDataLayoutDatasourcesDataSourceIdRoute,
    LayoutDataLayoutDatasourcesIndexRoute:
      LayoutDataLayoutDatasourcesIndexRoute,
  }

const LayoutDataLayoutDatasourcesRouteWithChildren =
  LayoutDataLayoutDatasourcesRoute._addFileChildren(
    LayoutDataLayoutDatasourcesRouteChildren,
  )

interface LayoutDataRouteChildren {
  LayoutDataLayoutDatasourcesRoute: typeof LayoutDataLayoutDatasourcesRouteWithChildren
}

const LayoutDataRouteChildren: LayoutDataRouteChildren = {
  LayoutDataLayoutDatasourcesRoute:
    LayoutDataLayoutDatasourcesRouteWithChildren,
}

const LayoutDataRouteWithChildren = LayoutDataRoute._addFileChildren(
  LayoutDataRouteChildren,
)

interface LayoutModelsLayoutModelsRouteChildren {
  LayoutModelsLayoutModelsIndexRoute: typeof LayoutModelsLayoutModelsIndexRoute
}

const LayoutModelsLayoutModelsRouteChildren: LayoutModelsLayoutModelsRouteChildren =
  {
    LayoutModelsLayoutModelsIndexRoute: LayoutModelsLayoutModelsIndexRoute,
  }

const LayoutModelsLayoutModelsRouteWithChildren =
  LayoutModelsLayoutModelsRoute._addFileChildren(
    LayoutModelsLayoutModelsRouteChildren,
  )

interface LayoutModelsRouteChildren {
  LayoutModelsLayoutModelsRoute: typeof LayoutModelsLayoutModelsRouteWithChildren
}

const LayoutModelsRouteChildren: LayoutModelsRouteChildren = {
  LayoutModelsLayoutModelsRoute: LayoutModelsLayoutModelsRouteWithChildren,
}

const LayoutModelsRouteWithChildren = LayoutModelsRoute._addFileChildren(
  LayoutModelsRouteChildren,
)

interface LayoutProjectsLayoutProjectsRouteChildren {
  LayoutProjectsLayoutProjectsProjectIdRoute: typeof LayoutProjectsLayoutProjectsProjectIdRoute
  LayoutProjectsLayoutProjectsIndexRoute: typeof LayoutProjectsLayoutProjectsIndexRoute
}

const LayoutProjectsLayoutProjectsRouteChildren: LayoutProjectsLayoutProjectsRouteChildren =
  {
    LayoutProjectsLayoutProjectsProjectIdRoute:
      LayoutProjectsLayoutProjectsProjectIdRoute,
    LayoutProjectsLayoutProjectsIndexRoute:
      LayoutProjectsLayoutProjectsIndexRoute,
  }

const LayoutProjectsLayoutProjectsRouteWithChildren =
  LayoutProjectsLayoutProjectsRoute._addFileChildren(
    LayoutProjectsLayoutProjectsRouteChildren,
  )

interface LayoutProjectsRouteChildren {
  LayoutProjectsLayoutProjectsRoute: typeof LayoutProjectsLayoutProjectsRouteWithChildren
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsLayoutProjectsRoute:
    LayoutProjectsLayoutProjectsRouteWithChildren,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRouteWithChildren
  LayoutDataRoute: typeof LayoutDataRouteWithChildren
  LayoutModelsRoute: typeof LayoutModelsRouteWithChildren
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
  LayoutSessionsSessionIdRoute: typeof LayoutSessionsSessionIdRoute
  LayoutSessionsIndexRoute: typeof LayoutSessionsIndexRoute
  LayoutChatProjectsProjectIdRoute: typeof LayoutChatProjectsProjectIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnalyticsRoute: LayoutAnalyticsRouteWithChildren,
  LayoutDataRoute: LayoutDataRouteWithChildren,
  LayoutModelsRoute: LayoutModelsRouteWithChildren,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
  LayoutSessionsSessionIdRoute: LayoutSessionsSessionIdRoute,
  LayoutSessionsIndexRoute: LayoutSessionsIndexRoute,
  LayoutChatProjectsProjectIdRoute: LayoutChatProjectsProjectIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/analytics': typeof LayoutAnalyticsLayoutModelsRouteWithChildren
  '/data': typeof LayoutDataLayoutDatasourcesRouteWithChildren
  '/models': typeof LayoutModelsLayoutModelsRouteWithChildren
  '/projects': typeof LayoutProjectsLayoutProjectsRouteWithChildren
  '/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/chat/projects/$projectId': typeof LayoutChatProjectsProjectIdRoute
  '/data/$dataSourceId': typeof LayoutDataLayoutDatasourcesDataSourceIdRoute
  '/projects/$projectId': typeof LayoutProjectsLayoutProjectsProjectIdRoute
  '/analytics/': typeof LayoutAnalyticsLayoutModelsIndexRoute
  '/data/': typeof LayoutDataLayoutDatasourcesIndexRoute
  '/models/': typeof LayoutModelsLayoutModelsIndexRoute
  '/projects/': typeof LayoutProjectsLayoutProjectsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/analytics': typeof LayoutAnalyticsLayoutModelsIndexRoute
  '/data': typeof LayoutDataLayoutDatasourcesIndexRoute
  '/models': typeof LayoutModelsLayoutModelsIndexRoute
  '/projects': typeof LayoutProjectsLayoutProjectsIndexRoute
  '/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/chat/projects/$projectId': typeof LayoutChatProjectsProjectIdRoute
  '/data/$dataSourceId': typeof LayoutDataLayoutDatasourcesDataSourceIdRoute
  '/projects/$projectId': typeof LayoutProjectsLayoutProjectsProjectIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/analytics': typeof LayoutAnalyticsRouteWithChildren
  '/_layout/analytics/_layout-models': typeof LayoutAnalyticsLayoutModelsRouteWithChildren
  '/_layout/data': typeof LayoutDataRouteWithChildren
  '/_layout/data/_layout-datasources': typeof LayoutDataLayoutDatasourcesRouteWithChildren
  '/_layout/models': typeof LayoutModelsRouteWithChildren
  '/_layout/models/_layout-models': typeof LayoutModelsLayoutModelsRouteWithChildren
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/_layout/projects/_layout-projects': typeof LayoutProjectsLayoutProjectsRouteWithChildren
  '/_layout/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
  '/_layout/sessions/': typeof LayoutSessionsIndexRoute
  '/_layout/chat/projects/$projectId': typeof LayoutChatProjectsProjectIdRoute
  '/_layout/data/_layout-datasources/$dataSourceId': typeof LayoutDataLayoutDatasourcesDataSourceIdRoute
  '/_layout/projects/_layout-projects/$projectId': typeof LayoutProjectsLayoutProjectsProjectIdRoute
  '/_layout/analytics/_layout-models/': typeof LayoutAnalyticsLayoutModelsIndexRoute
  '/_layout/data/_layout-datasources/': typeof LayoutDataLayoutDatasourcesIndexRoute
  '/_layout/models/_layout-models/': typeof LayoutModelsLayoutModelsIndexRoute
  '/_layout/projects/_layout-projects/': typeof LayoutProjectsLayoutProjectsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/analytics'
    | '/data'
    | '/models'
    | '/projects'
    | '/sessions/$sessionId'
    | '/sessions'
    | '/chat/projects/$projectId'
    | '/data/$dataSourceId'
    | '/projects/$projectId'
    | '/analytics/'
    | '/data/'
    | '/models/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/analytics'
    | '/data'
    | '/models'
    | '/projects'
    | '/sessions/$sessionId'
    | '/sessions'
    | '/chat/projects/$projectId'
    | '/data/$dataSourceId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/analytics'
    | '/_layout/analytics/_layout-models'
    | '/_layout/data'
    | '/_layout/data/_layout-datasources'
    | '/_layout/models'
    | '/_layout/models/_layout-models'
    | '/_layout/projects'
    | '/_layout/projects/_layout-projects'
    | '/_layout/sessions/$sessionId'
    | '/_layout/sessions/'
    | '/_layout/chat/projects/$projectId'
    | '/_layout/data/_layout-datasources/$dataSourceId'
    | '/_layout/projects/_layout-projects/$projectId'
    | '/_layout/analytics/_layout-models/'
    | '/_layout/data/_layout-datasources/'
    | '/_layout/models/_layout-models/'
    | '/_layout/projects/_layout-projects/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/analytics",
        "/_layout/data",
        "/_layout/models",
        "/_layout/projects",
        "/_layout/sessions/$sessionId",
        "/_layout/sessions/",
        "/_layout/chat/projects/$projectId"
      ]
    },
    "/_layout/analytics": {
      "filePath": "_layout/analytics",
      "parent": "/_layout",
      "children": [
        "/_layout/analytics/_layout-models"
      ]
    },
    "/_layout/analytics/_layout-models": {
      "filePath": "_layout/analytics/_layout-models.tsx",
      "parent": "/_layout/analytics",
      "children": [
        "/_layout/analytics/_layout-models/"
      ]
    },
    "/_layout/data": {
      "filePath": "_layout/data",
      "parent": "/_layout",
      "children": [
        "/_layout/data/_layout-datasources"
      ]
    },
    "/_layout/data/_layout-datasources": {
      "filePath": "_layout/data/_layout-datasources.tsx",
      "parent": "/_layout/data",
      "children": [
        "/_layout/data/_layout-datasources/$dataSourceId",
        "/_layout/data/_layout-datasources/"
      ]
    },
    "/_layout/models": {
      "filePath": "_layout/models",
      "parent": "/_layout",
      "children": [
        "/_layout/models/_layout-models"
      ]
    },
    "/_layout/models/_layout-models": {
      "filePath": "_layout/models/_layout-models.tsx",
      "parent": "/_layout/models",
      "children": [
        "/_layout/models/_layout-models/"
      ]
    },
    "/_layout/projects": {
      "filePath": "_layout/projects",
      "parent": "/_layout",
      "children": [
        "/_layout/projects/_layout-projects"
      ]
    },
    "/_layout/projects/_layout-projects": {
      "filePath": "_layout/projects/_layout-projects.tsx",
      "parent": "/_layout/projects",
      "children": [
        "/_layout/projects/_layout-projects/$projectId",
        "/_layout/projects/_layout-projects/"
      ]
    },
    "/_layout/sessions/$sessionId": {
      "filePath": "_layout/sessions/$sessionId.tsx",
      "parent": "/_layout"
    },
    "/_layout/sessions/": {
      "filePath": "_layout/sessions/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/chat/projects/$projectId": {
      "filePath": "_layout/chat/projects/$projectId.tsx",
      "parent": "/_layout"
    },
    "/_layout/data/_layout-datasources/$dataSourceId": {
      "filePath": "_layout/data/_layout-datasources/$dataSourceId.tsx",
      "parent": "/_layout/data/_layout-datasources"
    },
    "/_layout/projects/_layout-projects/$projectId": {
      "filePath": "_layout/projects/_layout-projects/$projectId.tsx",
      "parent": "/_layout/projects/_layout-projects"
    },
    "/_layout/analytics/_layout-models/": {
      "filePath": "_layout/analytics/_layout-models/index.tsx",
      "parent": "/_layout/analytics/_layout-models"
    },
    "/_layout/data/_layout-datasources/": {
      "filePath": "_layout/data/_layout-datasources/index.tsx",
      "parent": "/_layout/data/_layout-datasources"
    },
    "/_layout/models/_layout-models/": {
      "filePath": "_layout/models/_layout-models/index.tsx",
      "parent": "/_layout/models/_layout-models"
    },
    "/_layout/projects/_layout-projects/": {
      "filePath": "_layout/projects/_layout-projects/index.tsx",
      "parent": "/_layout/projects/_layout-projects"
    }
  }
}
ROUTE_MANIFEST_END */
