name: LLM checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.BRANCH }}

      - name: Install uv
        run: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-local-path: "./llm-service/uv.lock"

      - name: Set up Python
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.10'
          cache: false

      - name: Install Python dependencies
        run: |
          uv python install
        working-directory: llm-service

      - name: Run ruff
        run: |
          uv run ruff check app
        working-directory: llm-service

      - name: Run mypy
        run: |
          uv run mypy app
        working-directory: llm-service

      - name: Test with pytest
        run: |
          uv run pytest -sxvvra
        working-directory: llm-service

